# IdentityRepository is an alias for IdentityVerificationRepository.
from repositories.identity_verification_repo import IdentityVerificationRepository

IdentityRepository = IdentityVerificationRepository
