"""
PDF generation service.

Generates:
  - Signing certificates (one page appended to signed contracts)
  - Timeline / audit-trail PDF exports

Requires fpdf2 (pip install fpdf2).
"""

import datetime
from typing import Any, Dict, List


def _make_pdf():
    from fpdf import FPDF  # noqa: PLC0415  # type: ignore[import-untyped]
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(20, 20, 20)
    return pdf


def generate_signing_certificate(signature_data: Dict[str, Any]) -> bytes:
    """Generate a PDF signing certificate page.

    Per ESIGN Act (15 U.S.C. § 7001) and PIPEDA requirements, each signed contract
    must have an audit record that identifies who signed, when, how identity was
    verified, and a cryptographic binding to the exact document that was signed.
    """
    pdf = _make_pdf()
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(31, 42, 51)   # #1F2A33 primary
    pdf.cell(0, 12, "ELECTRONIC SIGNATURE CERTIFICATE", ln=True, align="C")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(91, 127, 166)  # #5B7FA6 info
    pdf.cell(0, 6,
        "Generated by ClearClaim  ·  Governed by ESIGN Act 15 U.S.C. §7001 and PIPEDA",
        ln=True, align="C",
    )
    pdf.ln(6)

    # Compliance notice
    pdf.set_fill_color(244, 246, 247)
    pdf.set_text_color(50, 60, 70)
    pdf.set_font("Helvetica", "", 8)
    pdf.multi_cell(
        0, 5,
        "This certificate confirms that the party identified below electronically signed the "
        "referenced contract document. The signature was executed with explicit consent, "
        "two-factor authentication (TOTP), and a cryptographic hash binding the signer's "
        "identity to the exact document version. This record is immutable and forms part of "
        "the legal audit trail.",
        fill=True,
    )
    pdf.ln(6)

    # Fields table
    fields = [
        ("Signer (User ID)",      signature_data.get("user_id",               "—")),
        ("Email",                 signature_data.get("email",                  "—")),
        ("Timestamp (UTC)",       str(signature_data.get("signed_at",         "—"))[:19].replace("T", " ")),
        ("Device ID",             signature_data.get("device_id",             "—")),
        ("IP Address",            signature_data.get("ip_address",            "—")),
        ("TOTP Verified",         "Yes" if signature_data.get("totp_verified") else "No"),
        ("Contract Version ID",   signature_data.get("version_id",            "—")),
        ("Signature ID",          signature_data.get("signature_id",          "—")),
        ("Document Snapshot Hash (SHA-256)", str(signature_data.get("contract_snapshot_hash", "—"))),
    ]

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(31, 42, 51)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 8, "  Signature Record", fill=True, ln=True)

    for i, (label, value) in enumerate(fields):
        bg = (244, 246, 247) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.set_text_color(50, 60, 70)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(75, 7, f"  {label}", fill=True)
        pdf.set_font("Helvetica", "", 8)
        # Wrap long values (e.g. hashes)
        val_str = str(value or "—")
        if len(val_str) > 60:
            pdf.set_font("Courier", "", 7)
        pdf.multi_cell(0, 7, val_str, fill=True)

    pdf.ln(6)

    # Footer
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(130, 140, 150)
    exported_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pdf.multi_cell(
        0, 4,
        f"Certificate exported: {exported_at}. "
        "Verify integrity by recomputing the SHA-256 hash of the original signed document "
        "and comparing it against the Document Snapshot Hash above.",
    )

    return bytes(pdf.output())


def generate_timeline_pdf(events: List[Dict[str, Any]], title: str = "Audit Timeline") -> bytes:
    """Render the full audit chain as a searchable PDF.

    Events are sorted chronologically. Each card shows event type, actor,
    timestamp, and the chained SHA-256 hash.
    """
    pdf = _make_pdf()
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(31, 42, 51)
    pdf.cell(0, 12, title, ln=True, align="C")

    exported_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(91, 127, 166)
    pdf.cell(0, 5, f"Exported: {exported_at}", ln=True, align="C")
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(50, 60, 70)
    pdf.set_fill_color(244, 246, 247)
    pdf.multi_cell(
        0, 5,
        "This timeline is an export of the tamper-evident audit chain maintained by ClearClaim. "
        "Each entry is cryptographically linked to its predecessor via SHA-256 chaining. "
        "Any post-export modification will cause hash verification failures.",
        fill=True,
    )
    pdf.ln(6)

    sorted_events = sorted(events, key=lambda e: e.get("timestamp", ""))

    for i, event in enumerate(sorted_events):
        event_type = (event.get("event_type") or "unknown").replace("_", " ").title()
        ts_raw     = str(event.get("timestamp", ""))[:19].replace("T", " ")
        actor      = str(event.get("user_id") or "System")
        details    = str(event.get("details") or "")[:200]
        entry_hash = str(event.get("hash") or "")

        # Alternating row colour
        if i % 2 == 0:
            pdf.set_fill_color(248, 250, 250)
        else:
            pdf.set_fill_color(255, 255, 255)

        # Row header
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(31, 42, 51)
        pdf.cell(0, 7, f"  {i + 1}.  {event_type}", fill=True, ln=True)

        # Meta row
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(91, 127, 166)
        pdf.cell(55, 5, f"    Timestamp: {ts_raw}", fill=True)
        pdf.cell(0,  5, f"Actor: {actor}",           fill=True, ln=True)

        # Details
        if details:
            pdf.set_font("Helvetica", "I", 7)
            pdf.set_text_color(100, 110, 120)
            pdf.multi_cell(0, 4, f"    {details}", fill=True)

        # Hash
        if entry_hash:
            pdf.set_font("Courier", "", 6)
            pdf.set_text_color(130, 140, 150)
            pdf.cell(0, 4, f"    Hash: {entry_hash}", fill=True, ln=True)

        pdf.ln(1)

    # Page footer with page numbers
    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(160, 170, 180)
    pdf.cell(0, 5, f"Page {pdf.page_no()} — ClearClaim Audit Export", align="C")

    return bytes(pdf.output())
